// lib/pdf/page1Cover.ts
import { PdfCtx } from "@/lib/pdf/types";
import { ClientInfo, KPISummary } from "@/lib/types";
import { fmt } from "@/lib/formatters";

export async function drawCoverPage(
  ctx: PdfCtx,
  clientInfo: ClientInfo,
  kpis: KPISummary,
): Promise<void> {
  const { doc, W, H, br, bg, bb, dr, dg, db, cur, LF } = ctx;

  // Dark background + brand sidebar
  doc.setFillColor(10, 15, 30); doc.rect(0, 0, W, H, "F");
  doc.setFillColor(br, bg, bb); doc.rect(0, 0, 8, H, "F");
  // Decorative circles
  doc.setFillColor(br, bg, bb);
  doc.setGState(doc.GState({ opacity: 0.12 })); doc.circle(W + 10, -10, 90, "F");
  doc.setGState(doc.GState({ opacity: 0.07 })); doc.circle(W - 10, 30, 60, "F");
  doc.setGState(doc.GState({ opacity: 1 }));
  // Footer bar
  doc.setFillColor(dr, dg, db); doc.rect(0, H - 18, W, 18, "F");

  // Logo — preserve aspect ratio within 55×22 mm bounding box
  let logoBottom = 30;
  if (clientInfo.logoDataUrl) {
    try {
      const imgFmt = clientInfo.logoDataUrl.startsWith('data:image/jpeg') || clientInfo.logoDataUrl.startsWith('data:image/jpg')
        ? 'JPEG'
        : clientInfo.logoDataUrl.startsWith('data:image/webp')
          ? 'WEBP'
          : 'PNG';
      const img = new Image();
      img.src = clientInfo.logoDataUrl;
      await new Promise<void>(r => { img.onload = () => r(); });
      const ratio = img.naturalWidth / img.naturalHeight;
      const maxW = 55, maxH = 22;
      const w = ratio > maxW / maxH ? maxW : maxH * ratio;
      const h = ratio > maxW / maxH ? maxW / ratio : maxH;
      doc.addImage(clientInfo.logoDataUrl, imgFmt, 24, 22, w, h);
      logoBottom = 22 + h + 8;
    } catch { /**/ }
  }

  // Report label + divider
  doc.setFontSize(8); LF("bold"); doc.setTextColor(br, bg, bb);
  doc.text("CAMPAIGN PERFORMANCE REPORT", 24, logoBottom + 16);
  doc.setDrawColor(br, bg, bb); doc.setLineWidth(0.4);
  doc.line(24, logoBottom + 20, W - 20, logoBottom + 20);

  // Client name — Arabic text renders as-is (jsPDF has no shaping support regardless of font)
  const cName = clientInfo.clientName || "Client Name";
  doc.setTextColor(241, 245, 249); doc.setFontSize(36);
  LF("bold"); doc.text(doc.splitTextToSize(cName, W - 44), 24, logoBottom + 56);
  LF("normal");

  // Agency + date
  if (clientInfo.agencyName) {
    doc.setFontSize(11); doc.setTextColor(br, bg, bb);
    LF("normal"); doc.text(clientInfo.agencyName, 24, logoBottom + 76);
  }
  if (clientInfo.dateFrom && clientInfo.dateTo) {
    doc.setFontSize(10); doc.setTextColor(148, 163, 184);
    doc.text(`${clientInfo.dateFrom}  to  ${clientInfo.dateTo}`, 24, logoBottom + 90);
  }

  // KPI mini-grid
  const coverKPIs = [
    { label: "Total Spend",  value: fmt(kpis.totalSpend,        "currency", cur) },
    { label: "Avg ROAS",     value: fmt(kpis.avgROAS,           "decimal")  + "x" },
    { label: "Avg CPA",      value: fmt(kpis.avgCPA,            "currency", cur) },
    { label: "Conversions",  value: fmt(kpis.totalConversions,  "number") },
    { label: "Impressions",  value: fmt(kpis.totalImpressions,  "number") },
    { label: "Avg CTR",      value: fmt(kpis.avgCTR,            "percent") },
  ];
  const bW = 54, bH = 28, bGap = 8, bCols = 3;
  const bSX = 24, bSY = H - 18 - 10 - Math.ceil(coverKPIs.length / bCols) * (bH + bGap);
  coverKPIs.forEach(({ label, value }, i) => {
    const x = bSX + (i % bCols) * (bW + bGap), y = bSY + Math.floor(i / bCols) * (bH + bGap);
    doc.setFillColor(255, 255, 255); doc.setGState(doc.GState({ opacity: 0.06 }));
    doc.roundedRect(x, y, bW, bH, 2, 2, "F"); doc.setGState(doc.GState({ opacity: 1 }));
    doc.setFillColor(br, bg, bb); doc.rect(x, y, 2, bH, "F");
    doc.setFontSize(6);  LF("normal"); doc.setTextColor(148, 163, 184); doc.text(label,  x + 5, y + 8);
    doc.setFontSize(11); LF("bold");   doc.setTextColor(241, 245, 249); doc.text(value,  x + 5, y + 20);
  });

  doc.setFontSize(7); LF("normal"); doc.setTextColor(100, 116, 139);
  doc.text("Generated by MetriQuill Free  ·  metriquill.com/free  ·  Confidential", 24, H - 6);
}
