"use client";

import { useState } from "react";
import { CampaignData, ClientInfo } from "@/lib/types";
import { fmt } from "@/lib/formatters";

interface Props {
  campaigns: CampaignData[];
  clientInfo: ClientInfo;
  kpis: Record<string, number>;
}

export default function ExportButtons({ campaigns, clientInfo, kpis }: Props) {
  const [pdfLoading, setPdfLoading] = useState(false);
  const [pngLoading, setPngLoading] = useState(false);

  const exportCSV = () => {
    const headers = ["Campaign","Spend","Impressions","Clicks","CTR","CPC","CPM","Conversions","ROAS"];
    const rows = campaigns.map(c => [
      c.name, c.spend, c.impressions, c.clicks,
      c.ctr.toFixed(2), c.cpc.toFixed(2), c.cpm.toFixed(2),
      c.conversions, c.roas.toFixed(2),
    ]);
    const csv = [headers, ...rows].map(r => r.join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `metriquill-${clientInfo.clientName || "report"}.csv`;
    a.click(); URL.revokeObjectURL(url);
  };

  const exportPNG = async () => {
    setPngLoading(true);
    try {
      const W = 1200; const H = 675;
      const canvas = document.createElement("canvas");
      canvas.width = W; canvas.height = H;
      const ctx = canvas.getContext("2d")!;

      // Load Inter font
      try {
        const font = new FontFace("Inter", "url(https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiJ-Ek-_EeA.woff2)");
        await font.load();
        document.fonts.add(font);
      } catch { /* fallback to system font */ }

      const brand = /^#[0-9A-Fa-f]{6}$/.test(clientInfo.brandColor) ? clientInfo.brandColor : "#2563EB";

      // Background gradient
      const grad = ctx.createLinearGradient(0, 0, W, H);
      grad.addColorStop(0, "#080C14");
      grad.addColorStop(1, "#0f1a2e");
      ctx.fillStyle = grad;
      ctx.fillRect(0, 0, W, H);

      // Brand accent bar top
      ctx.fillStyle = brand;
      ctx.fillRect(0, 0, W, 6);

      // Decorative circle
      ctx.beginPath();
      ctx.arc(W - 80, 80, 120, 0, Math.PI * 2);
      ctx.fillStyle = brand + "22";
      ctx.fill();

      // Logo (if present)
      if (clientInfo.logoDataUrl) {
        try {
          const img = new Image();
          await new Promise<void>((res, rej) => {
            img.onload = () => res();
            img.onerror = () => rej();
            img.src = clientInfo.logoDataUrl;
          });
          ctx.drawImage(img, 60, 50, 120, 50);
        } catch { /* skip logo */ }
      }

      // Title
      ctx.fillStyle = "#ffffff";
      ctx.font = "bold 52px Inter, sans-serif";
      ctx.fillText(clientInfo.clientName || "Campaign Report", 60, clientInfo.logoDataUrl ? 160 : 120);

      ctx.font = "24px Inter, sans-serif";
      ctx.fillStyle = "#94a3b8";
      const period = clientInfo.dateFrom && clientInfo.dateTo
        ? `${clientInfo.dateFrom} → ${clientInfo.dateTo}`
        : "Performance Summary";
      ctx.fillText(period, 60, clientInfo.logoDataUrl ? 200 : 160);

      // KPI cards (3 key metrics)
      const metricCards = [
        { label: "Total Spend", value: fmt(kpis.totalSpend, "currency", clientInfo.currency) },
        { label: "Avg ROAS", value: fmt(kpis.avgROAS, "decimal") + "x" },
        { label: "Conversions", value: fmt(kpis.totalConversions, "number") },
        { label: "Avg CTR", value: fmt(kpis.avgCTR, "percent") },
      ];

      const cardW = 240; const cardH = 110;
      const startX = 60; const cardY = 340;
      const gap = 24;

      metricCards.forEach((m, i) => {
        const x = startX + i * (cardW + gap);
        // Card bg
        ctx.fillStyle = "#ffffff14";
        roundRect(ctx, x, cardY, cardW, cardH, 12);
        ctx.fill();
        // Left border accent
        ctx.fillStyle = brand;
        roundRect(ctx, x, cardY, 4, cardH, 2);
        ctx.fill();

        ctx.fillStyle = "#94a3b8";
        ctx.font = "16px Inter, sans-serif";
        ctx.fillText(m.label, x + 20, cardY + 38);

        ctx.fillStyle = "#ffffff";
        ctx.font = "bold 32px Inter, sans-serif";
        ctx.fillText(m.value, x + 20, cardY + 82);
      });

      // Divider
      ctx.strokeStyle = "#ffffff20";
      ctx.lineWidth = 1;
      ctx.beginPath();
      ctx.moveTo(60, 500); ctx.lineTo(W - 60, 500);
      ctx.stroke();

      // Footer
      ctx.font = "14px Inter, sans-serif";
      ctx.fillStyle = "#64748b";
      ctx.fillText("Generated by MetriQuill Free · metriquill.com/free", 60, 535);

      if (clientInfo.agencyName) {
        ctx.textAlign = "right";
        ctx.fillText(clientInfo.agencyName, W - 60, 535);
        ctx.textAlign = "left";
      }

      // Download
      canvas.toBlob(blob => {
        if (!blob) return;
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `metriquill-${clientInfo.clientName || "report"}.png`;
        a.click();
        URL.revokeObjectURL(url);
      }, "image/png");

    } catch (e) {
      console.error(e);
    } finally {
      setPngLoading(false);
    }
  };

  const exportPDF = async () => {
    setPdfLoading(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const W = 210; const H = 297;
      const brand = /^#[0-9A-Fa-f]{6}$/.test(clientInfo.brandColor) ? clientInfo.brandColor : "#2563EB";
      const r = parseInt(brand.slice(1,3),16);
      const g = parseInt(brand.slice(3,5),16);
      const b = parseInt(brand.slice(5,7),16);

      // Cover page
      doc.setFillColor(r, g, b);
      doc.rect(0, 0, W, H, "F");
      doc.setFillColor(255,255,255);
      doc.circle(W - 30, 60, 80, "F");

      if (clientInfo.logoDataUrl) {
        try { doc.addImage(clientInfo.logoDataUrl, "PNG", 20, 20, 40, 20); } catch {}
      }

      doc.setTextColor(255,255,255);
      doc.setFontSize(32); doc.setFont("helvetica","bold");
      doc.text("Campaign", 20, 100);
      doc.text("Performance", 20, 115);
      doc.text("Report", 20, 130);

      doc.setFontSize(13); doc.setFont("helvetica","normal");
      doc.text(`Client: ${clientInfo.clientName || "—"}`, 20, 155);
      doc.text(`Agency: ${clientInfo.agencyName || "—"}`, 20, 163);
      if (clientInfo.dateFrom && clientInfo.dateTo) {
        doc.text(`Period: ${clientInfo.dateFrom} - ${clientInfo.dateTo}`, 20, 171);
      }

      doc.setFontSize(9); doc.setTextColor(255,255,255);
      doc.text("Generated by MetriQuill Free · metriquill.com/free · Confidential", 20, H - 10);

      // KPI page
      doc.addPage();
      doc.setFillColor(248,250,252); doc.rect(0,0,W,H,"F");
      doc.setTextColor(15,23,42); doc.setFontSize(18); doc.setFont("helvetica","bold");
      doc.text("Performance Summary", 20, 25);
      doc.setDrawColor(r,g,b); doc.setLineWidth(0.5); doc.line(20,29,W-20,29);

      const kpiItems = [
        ["Total Spend", fmt(kpis.totalSpend,"currency",clientInfo.currency)],
        ["Impressions", fmt(kpis.totalImpressions,"number")],
        ["Reach", fmt(kpis.totalReach,"number")],
        ["Avg Frequency", fmt(kpis.avgFrequency,"decimal")+"x"],
        ["Clicks", fmt(kpis.totalClicks,"number")],
        ["Avg CTR", fmt(kpis.avgCTR,"percent")],
        ["Avg CPC", fmt(kpis.avgCPC,"currency",clientInfo.currency)],
        ["CPM", fmt(kpis.avgCPM,"currency",clientInfo.currency)],
        ["Conversions", fmt(kpis.totalConversions,"number")],
        ["Avg ROAS", fmt(kpis.avgROAS,"decimal")+"x"],
      ];

      kpiItems.forEach(([label, value], i) => {
        const col = i % 2; const row = Math.floor(i / 2);
        const x = 20 + col * 90; const y = 50 + row * 28;
        doc.setFillColor(255,255,255); doc.roundedRect(x, y, 82, 22, 3, 3, "F");
        doc.setFontSize(7); doc.setFont("helvetica","normal"); doc.setTextColor(100,116,139);
        doc.text(label, x+6, y+8);
        doc.setFontSize(13); doc.setFont("helvetica","bold"); doc.setTextColor(r,g,b);
        doc.text(value, x+6, y+17);
      });

      // Campaign table page
      doc.addPage();
      doc.setFillColor(248,250,252); doc.rect(0,0,W,H,"F");
      doc.setTextColor(15,23,42); doc.setFontSize(18); doc.setFont("helvetica","bold");
      doc.text("Campaign Breakdown", 20, 25);
      doc.setDrawColor(r,g,b); doc.setLineWidth(0.5); doc.line(20,29,W-20,29);

      const cols = ["Campaign","Spend","CTR","CPC","ROAS"];
      const colX = [20, 110, 140, 158, 178];
      doc.setFontSize(8); doc.setFont("helvetica","bold"); doc.setTextColor(100,116,139);
      cols.forEach((c, i) => doc.text(c, colX[i], 42));
      doc.setLineWidth(0.3); doc.setDrawColor(226,232,240); doc.line(20,45,W-20,45);

      campaigns.forEach((c, i) => {
        const y = 52 + i * 12;
        if (y > H - 20) return;
        if (i % 2 === 0) { doc.setFillColor(248,250,252); doc.rect(20,y-5,W-40,11,"F"); }
        doc.setFontSize(8); doc.setFont("helvetica","normal"); doc.setTextColor(15,23,42);
        // Strip non-latin chars jsPDF helvetica can't render (Arabic, emoji etc.)
        const cleanName = c.name.replace(/[^\x00-\x7F\u00C0-\u024F]/g, '').trim() || c.name.slice(0, 20);
        const name = cleanName.length > 35 ? cleanName.slice(0,35)+"..." : cleanName;
        doc.text(name, 20, y);
        doc.text(fmt(c.spend,"currency",clientInfo.currency), 110, y);
        doc.text(fmt(c.ctr,"percent"), 140, y);
        doc.text(fmt(c.cpc,"currency",clientInfo.currency), 158, y);
        const roasColor = c.roas >= 3 ? [5,150,105] : c.roas >= 1.5 ? [217,119,6] : [220,38,38];
        doc.setTextColor(roasColor[0],roasColor[1],roasColor[2]);
        doc.text(c.roas > 0 ? fmt(c.roas,"decimal")+"x" : "—", 178, y);
        doc.setTextColor(15,23,42);
      });

      doc.setFontSize(8); doc.setTextColor(100,116,139);
      doc.text("metriquill.com/free", W/2, H-8, { align: "center" });

      doc.save(`metriquill-${clientInfo.clientName || "report"}.pdf`);
    } catch (e) {
      console.error(e);
    } finally {
      setPdfLoading(false);
    }
  };

  const btnStyle = (primary?: boolean, gradient?: boolean): React.CSSProperties => ({
    padding: "11px 22px", borderRadius: 8, fontWeight: 600, fontSize: 14,
    cursor: "pointer", border: primary || gradient ? "none" : "1px solid var(--border)",
    background: gradient
      ? "linear-gradient(135deg,#1e40af,#7c3aed)"
      : primary ? "var(--blue)" : "var(--surface)",
    color: primary || gradient ? "white" : "var(--text)",
    display: "flex", alignItems: "center", gap: 8,
    textDecoration: "none",
  });

  return (
    <div style={{
      background: "var(--surface)", borderRadius: "var(--radius)",
      boxShadow: "var(--shadow)", padding: "20px 24px",
      display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap",
    }}>
      <span style={{ fontWeight: 600, fontSize: 15, marginRight: 8 }}>Export:</span>
      <button onClick={exportPDF} disabled={pdfLoading} style={btnStyle(true)}>
        <span className={pdfLoading ? "spinning" : ""} style={{ display: "inline-block" }}>
          {pdfLoading ? "⏳" : "📄"}
        </span>
        {pdfLoading ? "Generating PDF…" : "Download PDF"}
      </button>
      <button onClick={exportPNG} disabled={pngLoading} style={btnStyle()}>
        <span className={pngLoading ? "spinning" : ""} style={{ display: "inline-block" }}>
          {pngLoading ? "⏳" : "🖼️"}
        </span>
        {pngLoading ? "Generating PNG…" : "Export PNG"}
      </button>
      <button onClick={exportCSV} style={btnStyle()}>📊 Export CSV</button>
      <a
        href="https://metriquill.com?utm_source=metriquill-free&utm_medium=export-bar&utm_campaign=upgrade"
        target="_blank"
        rel="noopener noreferrer"
        style={{ ...btnStyle(false, true), marginLeft: "auto" }}
      >
        ⚡ Try MetriQuill Pro
      </a>
    </div>
  );
}

// Helper: rounded rect for canvas
function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}
