"use client";

import { useState } from "react";
import { CampaignData, ClientInfo } from "@/lib/types";
import { fmt } from "@/lib/formatters";

interface Props {
  campaigns: CampaignData[];
  clientInfo: ClientInfo;
  kpis: Record<string, number>;
}

export default function ExportButtons({ campaigns, clientInfo, kpis }: Props) {
  const [pdfLoading, setPdfLoading] = useState(false);

  const exportCSV = () => {
    const headers = ["Campaign","Spend","Impressions","Clicks","CTR","CPC","CPM","Conversions","ROAS"];
    const rows = campaigns.map(c => [
      c.name, c.spend, c.impressions, c.clicks,
      c.ctr.toFixed(2), c.cpc.toFixed(2), c.cpm.toFixed(2),
      c.conversions, c.roas.toFixed(2),
    ]);
    const csv = [headers, ...rows].map(r => r.join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `metriquill-${clientInfo.clientName || "report"}.csv`;
    a.click(); URL.revokeObjectURL(url);
  };

  const exportPDF = async () => {
    setPdfLoading(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const W = 210; const H = 297;
      const brand = /^#[0-9A-Fa-f]{6}$/.test(clientInfo.brandColor) ? clientInfo.brandColor : "#2563EB";
      const r = parseInt(brand.slice(1,3),16);
      const g = parseInt(brand.slice(3,5),16);
      const b = parseInt(brand.slice(5,7),16);

      // Cover page
      doc.setFillColor(r, g, b);
      doc.rect(0, 0, W, H, "F");
      doc.setFillColor(255,255,255,0.08);
      doc.circle(W - 30, 60, 80, "F");

      if (clientInfo.logoDataUrl) {
        try { doc.addImage(clientInfo.logoDataUrl, "PNG", 20, 20, 40, 20); } catch {}
      }

      doc.setTextColor(255,255,255);
      doc.setFontSize(32); doc.setFont("helvetica","bold");
      doc.text("Campaign", 20, 100);
      doc.text("Performance", 20, 115);
      doc.text("Report", 20, 130);

      doc.setFontSize(13); doc.setFont("helvetica","normal");
      doc.text(`Client: ${clientInfo.clientName || "—"}`, 20, 155);
      doc.text(`Agency: ${clientInfo.agencyName || "—"}`, 20, 163);
      if (clientInfo.dateFrom && clientInfo.dateTo) {
        doc.text(`Period: ${clientInfo.dateFrom} → ${clientInfo.dateTo}`, 20, 171);
      }

      doc.setFontSize(9); doc.setTextColor(255,255,255,0.6);
      doc.text("Generated by MetriQuill Free · metriquill.com/free · Confidential", 20, H - 10);

      // KPI page
      doc.addPage();
      doc.setFillColor(248,250,252); doc.rect(0,0,W,H,"F");
      doc.setTextColor(15,23,42); doc.setFontSize(18); doc.setFont("helvetica","bold");
      doc.text("Performance Summary", 20, 25);
      doc.setDrawColor(r,g,b); doc.setLineWidth(0.5); doc.line(20,29,W-20,29);

      const kpiItems = [
        ["Total Spend", fmt(kpis.totalSpend,"currency",clientInfo.currency)],
        ["Impressions", fmt(kpis.totalImpressions,"number")],
        ["Clicks", fmt(kpis.totalClicks,"number")],
        ["Avg CTR", fmt(kpis.avgCTR,"percent")],
        ["Avg CPC", fmt(kpis.avgCPC,"currency",clientInfo.currency)],
        ["CPM", fmt(kpis.avgCPM,"currency",clientInfo.currency)],
        ["Conversions", fmt(kpis.totalConversions,"number")],
        ["Avg ROAS", fmt(kpis.avgROAS,"decimal")+"x"],
      ];

      kpiItems.forEach(([label, value], i) => {
        const col = i % 2; const row = Math.floor(i / 2);
        const x = 20 + col * 90; const y = 50 + row * 28;
        doc.setFillColor(255,255,255); doc.roundedRect(x, y, 82, 22, 3, 3, "F");
        doc.setFontSize(7); doc.setFont("helvetica","normal"); doc.setTextColor(100,116,139);
        doc.text(label, x+6, y+8);
        doc.setFontSize(13); doc.setFont("helvetica","bold"); doc.setTextColor(r,g,b);
        doc.text(value, x+6, y+17);
      });

      // Campaign table page
      doc.addPage();
      doc.setFillColor(248,250,252); doc.rect(0,0,W,H,"F");
      doc.setTextColor(15,23,42); doc.setFontSize(18); doc.setFont("helvetica","bold");
      doc.text("Campaign Breakdown", 20, 25);
      doc.setDrawColor(r,g,b); doc.setLineWidth(0.5); doc.line(20,29,W-20,29);

      const cols = ["Campaign","Spend","CTR","CPC","ROAS"];
      const colX = [20, 110, 140, 158, 178];
      doc.setFontSize(8); doc.setFont("helvetica","bold"); doc.setTextColor(100,116,139);
      cols.forEach((c, i) => doc.text(c, colX[i], 42));
      doc.setLineWidth(0.3); doc.setDrawColor(226,232,240); doc.line(20,45,W-20,45);

      campaigns.forEach((c, i) => {
        const y = 52 + i * 12;
        if (y > H - 20) return;
        if (i % 2 === 0) { doc.setFillColor(248,250,252); doc.rect(20,y-5,W-40,11,"F"); }
        doc.setFontSize(8); doc.setFont("helvetica","normal"); doc.setTextColor(15,23,42);
        const name = c.name.length > 35 ? c.name.slice(0,35)+"…" : c.name;
        doc.text(name, 20, y);
        doc.text(fmt(c.spend,"currency",clientInfo.currency), 110, y);
        doc.text(fmt(c.ctr,"percent"), 140, y);
        doc.text(fmt(c.cpc,"currency",clientInfo.currency), 158, y);
        const roasColor = c.roas >= 3 ? [5,150,105] : c.roas >= 1.5 ? [217,119,6] : [220,38,38];
        doc.setTextColor(roasColor[0],roasColor[1],roasColor[2]);
        doc.text(c.roas > 0 ? fmt(c.roas,"decimal")+"x" : "—", 178, y);
        doc.setTextColor(15,23,42);
      });

      doc.setFontSize(8); doc.setTextColor(100,116,139);
      doc.text("metriquill.com/free", W/2, H-8, { align: "center" });

      doc.save(`metriquill-${clientInfo.clientName || "report"}.pdf`);
    } catch (e) {
      console.error(e);
    } finally {
      setPdfLoading(false);
    }
  };

  const btnStyle = (primary?: boolean): React.CSSProperties => ({
    padding: "11px 22px", borderRadius: 8, fontWeight: 600, fontSize: 14,
    cursor: "pointer", border: primary ? "none" : "1px solid var(--border)",
    background: primary ? "var(--blue)" : "var(--surface)",
    color: primary ? "white" : "var(--text)",
    display: "flex", alignItems: "center", gap: 8,
  });

  return (
    <div style={{
      background: "var(--surface)", borderRadius: "var(--radius)",
      boxShadow: "var(--shadow)", padding: "20px 24px",
      display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap",
    }}>
      <span style={{ fontWeight: 600, fontSize: 15, marginRight: 8 }}>Export:</span>
      <button onClick={exportPDF} disabled={pdfLoading} style={btnStyle(true)}>
        <span className={pdfLoading ? "spinning" : ""} style={{ display: "inline-block" }}>
          {pdfLoading ? "⏳" : "📄"}
        </span>
        {pdfLoading ? "Generating PDF…" : "Download PDF"}
      </button>
      <button onClick={exportCSV} style={btnStyle()}>📊 Export CSV</button>
      <a
        href="https://metriquill.com"
        target="_blank"
        rel="noopener noreferrer"
        style={{
          ...btnStyle(), marginLeft: "auto",
          background: "linear-gradient(135deg,#1e40af,#7c3aed)",
          color: "white", border: "none", textDecoration: "none",
        }}
      >
        ⚡ Try MetriQuill Pro
      </a>
    </div>
  );
}
