// lib/buildPng.ts
// Exports a branded PNG cover card from report data.
// Called from ExportButtons (client-side only).

import { ClientInfo, KPISummary } from "./types";
import { fmt } from "./formatters";
import { hasArabic, reverseArabic, safeFilename } from "./textUtils";

function canvasRoundRect(
  ctx: CanvasRenderingContext2D,
  x: number, y: number, w: number, h: number, r: number
) {
  ctx.beginPath();
  ctx.moveTo(x + r, y); ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}

export async function buildPng(clientInfo: ClientInfo, kpis: KPISummary): Promise<void> {
  const W = 1200; const H = 675;
  const canvas = document.createElement("canvas");
  canvas.width = W; canvas.height = H;
  const ctx = canvas.getContext("2d")!;
  const brand = /^#[0-9A-Fa-f]{6}$/.test(clientInfo.brandColor) ? clientInfo.brandColor : "#2563EB";

  try {
    const [iF, aF] = await Promise.allSettled([
      new FontFace("Inter", "url(https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiJ-Ek-_EeA.woff2)").load(),
      new FontFace("Amiri", "url(https://fonts.gstatic.com/s/amiri/v27/J7aRnpd8CGxBHqUpvrIw74NL.woff2)").load(),
    ]);
    if (iF.status === "fulfilled") document.fonts.add(iF.value);
    if (aF.status === "fulfilled") document.fonts.add(aF.value);
  } catch { /* fallback */ }

  const grad = ctx.createLinearGradient(0, 0, W, H);
  grad.addColorStop(0, "#0a0f1e"); grad.addColorStop(1, "#111827");
  ctx.fillStyle = grad; ctx.fillRect(0, 0, W, H);
  ctx.fillStyle = brand; ctx.fillRect(0, 0, W, 5);
  ctx.beginPath(); ctx.arc(W + 40, -40, 260, 0, Math.PI * 2); ctx.fillStyle = brand + "18"; ctx.fill();
  ctx.beginPath(); ctx.arc(-30, H + 30, 160, 0, Math.PI * 2); ctx.fillStyle = brand + "12"; ctx.fill();

  const logoY = 48;
  if (clientInfo.logoDataUrl) {
    try {
      const img = new Image();
      await new Promise<void>((res, rej) => {
        img.onload = () => res(); img.onerror = () => rej(); img.src = clientInfo.logoDataUrl;
      });
      ctx.drawImage(img, 60, logoY, 110, 44);
    } catch { /* skip */ }
  }

  const nameY = clientInfo.logoDataUrl ? 160 : 120;
  const isAr  = hasArabic(clientInfo.clientName || "");
  ctx.fillStyle = "#ffffff";
  ctx.font = `bold 54px ${isAr ? "Amiri" : "Inter"}, sans-serif`;
  ctx.fillText(
    isAr ? reverseArabic(clientInfo.clientName || "") : (clientInfo.clientName || "Campaign Report"),
    60, nameY
  );
  ctx.font = "22px Inter, sans-serif"; ctx.fillStyle = "#64748b";
  const period = clientInfo.dateFrom && clientInfo.dateTo
    ? `${clientInfo.dateFrom}  →  ${clientInfo.dateTo}`
    : "Performance Summary";
  ctx.fillText(period, 60, nameY + 40);
  if (clientInfo.agencyName) {
    ctx.font = "16px Inter,sans-serif"; ctx.fillStyle = brand;
    ctx.fillText(clientInfo.agencyName.toUpperCase(), 60, nameY + 72);
  }

  const cards = [
    { label: "Total Spend",  value: fmt(kpis.totalSpend, "currency", clientInfo.currency), accent: brand },
    { label: "Avg ROAS",     value: fmt(kpis.avgROAS, "decimal") + "x",                    accent: "#10B981" },
    { label: "Avg CPA",      value: fmt(kpis.avgCPA, "currency", clientInfo.currency),     accent: "#F59E0B" },
    { label: "Avg CTR",      value: fmt(kpis.avgCTR, "percent"),                           accent: "#8B5CF6" },
  ];
  const cW = 245, cH = 115, cY = 460, cGap = 20;
  cards.forEach((card, i) => {
    const x = 60 + i * (cW + cGap);
    ctx.fillStyle = "#ffffff0d"; canvasRoundRect(ctx, x, cY, cW, cH, 12); ctx.fill();
    ctx.fillStyle = card.accent; canvasRoundRect(ctx, x, cY, cW, 3, 1); ctx.fill();
    ctx.fillStyle = "#64748b"; ctx.font = "14px Inter,sans-serif"; ctx.fillText(card.label, x + 18, cY + 30);
    ctx.fillStyle = "#f1f5f9"; ctx.font = "bold 30px Inter,sans-serif"; ctx.fillText(card.value, x + 18, cY + 78);
  });

  ctx.fillStyle = "#1e293b"; ctx.fillRect(0, H - 38, W, 38);
  ctx.font = "13px Inter,sans-serif"; ctx.fillStyle = "#475569"; ctx.textAlign = "left";
  ctx.fillText("Generated by MetriQuill Free  ·  metriquill.com/free", 60, H - 13);
  ctx.textAlign = "right"; ctx.fillStyle = "#64748b"; ctx.fillText("Confidential", W - 60, H - 13);
  ctx.textAlign = "left";

  canvas.toBlob(blob => {
    if (!blob) return;
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `metriquill-${safeFilename(clientInfo.clientName)}.png`;
    a.click();
    URL.revokeObjectURL(url);
  }, "image/png");
}
