// lib/pptx/coverSlide.ts
// Slide 1 — Branded cover with client name, period, and KPI callouts.

import { fmt } from "../formatters";
import { SlideCtx } from "./pptxHelpers";

export function buildCoverSlide(ctx: SlideCtx): void {
  const { pres, brand, brandDark, W, H, clientInfo, kpis } = ctx;
  const s = pres.addSlide();
  s.background = { color: "0A0F1E" };

  // Left brand sidebar
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0, y: 0, w: 0.18, h: H,
    fill: { color: brand }, line: { color: brand },
  });

  // Decorative circle accents
  s.addShape(pres.shapes.OVAL, {
    x: 7.8, y: -1.5, w: 3.5, h: 3.5,
    fill: { color: brand, transparency: 88 }, line: { color: brand, transparency: 88 },
  });
  s.addShape(pres.shapes.OVAL, {
    x: 8.5, y: -0.8, w: 2.0, h: 2.0,
    fill: { color: brand, transparency: 80 }, line: { color: brand, transparency: 80 },
  });

  // Logo
  if (clientInfo.logoDataUrl) {
    try { s.addImage({ data: clientInfo.logoDataUrl, x: 0.45, y: 0.3, w: 1.4, h: 0.55 }); } catch { /* skip */ }
  }

  // "CAMPAIGN PERFORMANCE REPORT" label
  s.addText("CAMPAIGN PERFORMANCE REPORT", {
    x: 0.45, y: clientInfo.logoDataUrl ? 1.05 : 0.7,
    w: 5.5, h: 0.25,
    fontSize: 8, bold: true, color: brand,
    charSpacing: 3, fontFace: "Calibri", margin: 0,
  });

  // Client name
  s.addText(clientInfo.clientName || "Campaign Report", {
    x: 0.45, y: clientInfo.logoDataUrl ? 1.35 : 1.0,
    w: 7, h: 1.5,
    fontSize: 40, bold: true, color: "F1F5F9",
    fontFace: "Calibri", margin: 0, wrap: true,
  });

  // Agency name
  if (clientInfo.agencyName) {
    s.addText(clientInfo.agencyName, {
      x: 0.45, y: 2.95, w: 5, h: 0.35,
      fontSize: 13, color: brand, fontFace: "Calibri", margin: 0,
    });
  }

  // Date period
  if (clientInfo.dateFrom && clientInfo.dateTo) {
    s.addText(`${clientInfo.dateFrom}  —  ${clientInfo.dateTo}`, {
      x: 0.45, y: 3.35, w: 5, h: 0.3,
      fontSize: 11, color: "64748B", fontFace: "Calibri", margin: 0,
    });
  }

  // 3 KPI callout boxes
  const coverKPIs = [
    { label: "Total Spend",  value: fmt(kpis.totalSpend, "currency", clientInfo.currency) },
    { label: "Avg ROAS",     value: fmt(kpis.avgROAS, "decimal") + "x" },
    { label: "Conversions",  value: fmt(kpis.totalConversions, "number") },
  ];
  const kpiBoxW = 2.4, kpiBoxH = 0.85, kpiBoxGap = 0.22;
  const kpiBoxY = H - kpiBoxH - 0.45;
  coverKPIs.forEach((k, i) => {
    const x = 0.45 + i * (kpiBoxW + kpiBoxGap);
    s.addShape(pres.shapes.RECTANGLE, {
      x, y: kpiBoxY, w: kpiBoxW, h: kpiBoxH,
      fill: { color: "FFFFFF", transparency: 93 }, line: { color: "FFFFFF", transparency: 93 },
    });
    s.addShape(pres.shapes.RECTANGLE, {
      x, y: kpiBoxY, w: kpiBoxW, h: 0.04,
      fill: { color: brand }, line: { color: brand },
    });
    s.addText(k.label, { x: x + 0.12, y: kpiBoxY + 0.1, w: kpiBoxW - 0.2, h: 0.22, fontSize: 8, color: "94A3B8", fontFace: "Calibri", margin: 0 });
    s.addText(k.value, { x: x + 0.12, y: kpiBoxY + 0.34, w: kpiBoxW - 0.2, h: 0.38, fontSize: 20, bold: true, color: "F1F5F9", fontFace: "Calibri", margin: 0 });
  });

  // Footer band
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0, y: H - 0.22, w: W, h: 0.22,
    fill: { color: brandDark }, line: { color: brandDark },
  });
  s.addText("Generated by MetriQuill Free  ·  metriquill.com/free  ·  Confidential", {
    x: 0.45, y: H - 0.2, w: 8, h: 0.18,
    fontSize: 7, color: "64748B", fontFace: "Calibri", margin: 0,
  });
}
