// lib/pptx/endSlide.ts
// Slide 6 — Thank You / closing branded slide.

import { SlideCtx } from "./pptxHelpers";

export function buildEndSlide(ctx: SlideCtx): void {
  const { pres, brand, H, clientInfo } = ctx;
  const s = pres.addSlide();
  s.background = { color: "0A0F1E" };

  // Left sidebar
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0, y: 0, w: 0.18, h: H,
    fill: { color: brand }, line: { color: brand },
  });

  // Decorative circle
  s.addShape(pres.shapes.OVAL, {
    x: -1, y: H - 2.5, w: 3.5, h: 3.5,
    fill: { color: brand, transparency: 88 }, line: { color: brand, transparency: 88 },
  });

  s.addText("Thank You", {
    x: 0.6, y: 1.6, w: 6, h: 0.9,
    fontSize: 44, bold: true, color: "F1F5F9", fontFace: "Calibri", margin: 0,
  });
  s.addText(clientInfo.agencyName || "MetriQuill", {
    x: 0.6, y: 2.55, w: 5, h: 0.45,
    fontSize: 14, color: brand, fontFace: "Calibri", margin: 0,
  });
  s.addText("Generated by MetriQuill Free  ·  metriquill.com/free", {
    x: 0.6, y: 3.1, w: 7, h: 0.3,
    fontSize: 9, color: "475569", fontFace: "Calibri", margin: 0,
  });
}
